### ISSUE TITLE
add Host and Port Options in deploy command

### ISSUE THREAD

**Issue by AndyWu2015** [gamerson/liferay-blade-cli#232]
As client request , we now decide to add -h and -p option back in deploy command.
add a NanoHTTPD.java server file (see bnd repo test sources for NanoHTTPD) and then when user uses this option for remote host we can have the install work over an http:// URL instead of 'file:///'

**Comment by hillier1** [comment]
Just saw the latest release of blade, doesnt' seem to include any fix for this. Is there any update on this?

**Comment by gamerson** [comment]
Now tracked by https://issues.liferay.com/browse/BLADE-189
