### ISSUE TITLE
update gradle-tooling-api to 2.14 and decrease the size of com.liferay.blade.cli.jar

### ISSUE THREAD

**Issue by AndyWu2015** [gamerson/liferay-blade-cli#76]
if we change the version of gradle-tooling-api to 2.14 , then we need another dependency gradle-core-2.14 , cause tooling-api lose some classes than 2.13 . that means , we need to include all classes in tooling-api and gradle-core , so the jar size will be bigger . We can only include the smallest closure of classes in org.gradle.*.

**Comment by gamerson** [comment]
Instead of including all of our "org.gradle.*" we can try to find the sub
packages to exactly what we need.

org.gradle.api.*
org.gradle.tooling.*
etc

Also we can try using the "Conditional-Package: org.gradle.*"



On Tue, Jul 5, 2016 at 3:50 AM, Andy Wu <notifications@github.com> wrote:

> if we change the version of gradle-tooling-api to 2.14 , then we need
> another dependency gradle-core-2.14 , cause tooling-api lose some classes
> than 2.13 . that means , we need to include all classes in tooling-api and
> gradle-core , so the jar size will be bigger . We can only include the
> smallest closure of classes in org.gradle.*.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gamerson/liferay-blade-cli/issues/76>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAkVFXReTPDireVhwy3Zxyf7D_YF98flks5qShrxgaJpZM4JE5uH>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by AndyWu2015** [comment]
yeah , that is exactly what I mean , and I will try "Conditional-Package" though I don't know what it is :)

**Comment by gamerson** [comment]
COnditionalPackage means "scan the classes and if any of the classes use
this package include it in the bundle otherwise exclude it.

On Tue, Jul 5, 2016 at 8:43 PM, Andy Wu <notifications@github.com> wrote:

> yeah , that is exactly what I mean , and I will try "Conditional-Package"
> though I don't know what it is :)
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/gamerson/liferay-blade-cli/issues/76#issuecomment-230650833>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAkVFUo-KZsosQoXyjtECkYncklUjsLYks5qSwgqgaJpZM4JE5uH>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by AndyWu2015** [comment]
Oh, it is a powerful tool.

**Comment by AndyWu2015** [comment]
hey Greg, I am sorry to say that biz.aQute.bnd.gradle plugin has some problem with gradle 2.14 .
When I run gradle clean build in com.liferay.blade.cli (using gradle 2.14 local install) , I got this :

`Caused by: java.lang.NullPointerException: Cannot set property 'project' on null object
        at aQute.bnd.gradle.BndPlugin$_apply_closure1.doCall(BndPlugin.groovy:64)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:107)
        at org.gradle.api.internal.project.AbstractProject.configure(AbstractProject.java:888)
        at org.gradle.api.Project$configure.call(Unknown Source)
        at aQute.bnd.gradle.BndPlugin.apply(BndPlugin.groovy:42)
        at aQute.bnd.gradle.BndPlugin.apply(BndPlugin.groovy)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPlugin
Applicator.java:35)
        at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator
.java:43)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:137)
        ... 64 more`

**Comment by AndyWu2015** [comment]
and all the tests in GradleToolingTest will fail except testCheckLatestArtifactVersionOnline
